// VietTypeATL.idl : IDL source for VietTypeATL
//

// This file will be processed by the MIDL tool to
// produce the type library (VietTypeATL.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

//[
    //object,
    //uuid(41039b47-45e0-400c-ae57-73e6f4427fdd),
    //pointer_default(unique)
//]
//interface TextService : IUnknown
//{
//};
[
    uuid(4914ef26-8318-4608-aa14-4f7cbb6229e5),
    version(1.0),
]
library VietTypeATLLib
{
    //importlib("stdole2.tlb");
    //[
        //uuid(c0dd01a1-0deb-454b-8b42-d22ced1b4b23)
    //]
    //coclass TextService
    //{
        //[default] interface TextService;
    //};
};

import "shobjidl.idl";
