//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTypeConfig2.LocalizedResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VietTypeConfig2.LocalizedResources.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VietType {0} ({1})
        ///Copyright © 2018 Dinh Ngoc Tu.
        ///VietType is free software, licensed under the GNU General Public License. VietType is distributed WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the included LICENSE file for more details..
        /// </summary>
        public static string MainWindow_AboutFormat {
            get {
                return ResourceManager.GetString("MainWindow_AboutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A_bout.
        /// </summary>
        public static string MainWindow_Button_About_Content {
            get {
                return ResourceManager.GetString("MainWindow_Button_About_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MainWindow_Button_Cancel_Content {
            get {
                return ResourceManager.GetString("MainWindow_Button_Cancel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MainWindow_Button_OK_Content {
            get {
                return ResourceManager.GetString("MainWindow_Button_OK_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept &apos;d&apos; any_where.
        /// </summary>
        public static string MainWindow_CheckBox_AcceptDd_Content {
            get {
                return ResourceManager.GetString("MainWindow_CheckBox_AcceptDd_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow &quot;đ&quot; abbre_viations.
        /// </summary>
        public static string MainWindow_CheckBox_AllowAbbreviations_Content {
            get {
                return ResourceManager.GetString("MainWindow_CheckBox_AllowAbbreviations_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable _autocorrect.
        /// </summary>
        public static string MainWindow_CheckBox_Autocorrect_Content {
            get {
                return ResourceManager.GetString("MainWindow_CheckBox_Autocorrect_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspaced _invalid word stays invalid.
        /// </summary>
        public static string MainWindow_CheckBox_BackspaceInvalid_Content {
            get {
                return ResourceManager.GetString("MainWindow_CheckBox_BackspaceInvalid_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese mode by de_fault.
        /// </summary>
        public static string MainWindow_CheckBox_DefaultEnabled_Content {
            get {
                return ResourceManager.GetString("MainWindow_CheckBox_DefaultEnabled_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Use &quot;oà&quot;, &quot;uý&quot; instead of &quot;òa&quot;, &quot;úy&quot;.
        /// </summary>
        public static string MainWindow_CheckBox_OaUyTone1_Content {
            get {
                return ResourceManager.GetString("MainWindow_CheckBox_OaUyTone1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Vietnamese interface.
        /// </summary>
        public static string MainWindow_CheckBox_VietnameseInterface_Content {
            get {
                return ResourceManager.GetString("MainWindow_CheckBox_VietnameseInterface_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully disabled VietType..
        /// </summary>
        public static string MainWindow_DisableOkText {
            get {
                return ResourceManager.GetString("MainWindow_DisableOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully enabled VietType. Switch to VietType in the language bar to start using it..
        /// </summary>
        public static string MainWindow_EnableOkText {
            get {
                return ResourceManager.GetString("MainWindow_EnableOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control settings.
        /// </summary>
        public static string MainWindow_GroupBox_ControlSettings_Header {
            get {
                return ResourceManager.GetString("MainWindow_GroupBox_ControlSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine settings.
        /// </summary>
        public static string MainWindow_GroupBox_EngineSettings_Header {
            get {
                return ResourceManager.GetString("MainWindow_GroupBox_EngineSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word _reconversion mode.
        /// </summary>
        public static string MainWindow_Label_Backconvert_Content {
            get {
                return ResourceManager.GetString("MainWindow_Label_Backconvert_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multilingual typing _optimization level:.
        /// </summary>
        public static string MainWindow_Label_OptimizeMultilang_Content {
            get {
                return ResourceManager.GetString("MainWindow_Label_OptimizeMultilang_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current word _highlight mode:.
        /// </summary>
        public static string MainWindow_Label_ShowComposingAttr_Content {
            get {
                return ResourceManager.GetString("MainWindow_Label_ShowComposingAttr_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Toggle key:.
        /// </summary>
        public static string MainWindow_Label_Toggle_Content {
            get {
                return ResourceManager.GetString("MainWindow_Label_Toggle_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing _style:.
        /// </summary>
        public static string MainWindow_Label_TypingStyle_Content {
            get {
                return ResourceManager.GetString("MainWindow_Label_TypingStyle_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VietType.
        /// </summary>
        public static string MainWindow_ProgramName {
            get {
                return ResourceManager.GetString("MainWindow_ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VietType Settings.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot configure VietType: {0}.
        /// </summary>
        public static string MainWindow_ToggleFailFormat {
            get {
                return ResourceManager.GetString("MainWindow_ToggleFailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Enable VietType.
        /// </summary>
        public static string MainWindowViewModel_IsEnabledText_False {
            get {
                return ResourceManager.GetString("MainWindowViewModel_IsEnabledText_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Disable VietType.
        /// </summary>
        public static string MainWindowViewModel_IsEnabledText_True {
            get {
                return ResourceManager.GetString("MainWindowViewModel_IsEnabledText_True", resourceCulture);
            }
        }
    }
}
