name: MSBuild

on:
  push:
    branches:
      - master
    paths-ignore:
      - "TestLib/**"
      - "VietTypeUnitTests/**"
      # unconditional
      - "TfDumper/**"
      - "WordLister/**"
      - "data/**"
      - "docs/**"
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions: {}

env:
  SOLUTION_FILE_PATH: .

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3

      - name: Restore Win32
        run: msbuild -m -target:Restore -p:Configuration=Release -p:Platform=Win32 .

      - name: Restore x64
        run: msbuild -m -target:Restore -p:Configuration=Release -p:Platform=x64 .

      - name: Build DLL Win32
        run: msbuild -m -target:VietTypeATL:Rebuild -p:Configuration=Release -p:Platform=Win32 .

      - name: Build DLL x64
        run: msbuild -m -target:VietTypeATL:Rebuild -p:Configuration=Release -p:Platform=x64 .

      - name: Build DLL ARM64X
        run: msbuild -m -target:VietTypeATL:Rebuild -p:Configuration=Release -p:Platform=ARM64EC .

      - name: Build Win32
        run: msbuild -m -target:VietTypeSetup:Rebuild -p:Configuration=Release -p:Platform=Win32 .

      - name: Build x64
        run: msbuild -m -target:VietTypeSetup:Rebuild -p:Configuration=Release -p:Platform=x64 .

      - name: Build ARM64X
        run: msbuild -m -target:VietTypeSetup:Rebuild -p:Configuration=Release -p:Platform=ARM64EC .

      - name: Upload a Build Artifact
        id: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: VietTypeSetup/bin/
          name: VietType

    outputs:
      subject-name: VietType
      subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}

  attest:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build]
    uses: dinhngtu/github-workflows/.github/workflows/attest.yml@f10ce70ad81acc4b9196bbda4617e799ffec1892
    permissions:
      id-token: write
      attestations: write
    with:
      subject-name: ${{ needs.build.outputs.subject-name }}
      subject-digest: ${{ needs.build.outputs.subject-digest }}
