name: MSBuild

on:
  release:
    types: [published]
  push:
    branches:
      - master

env:
  SOLUTION_FILE_PATH: .

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore Win32
        run: msbuild -m -target:Restore -p:Configuration=Release -p:Platform=Win32 .

      - name: Restore x64
        run: msbuild -m -target:Restore -p:Configuration=Release -p:Platform=x64 .

      - name: Build DLL Win32
        run: msbuild -m -target:VietTypeATL:Rebuild -p:Configuration=Release -p:Platform=Win32 .

      - name: Build DLL x64
        run: msbuild -m -target:VietTypeATL:Rebuild -p:Configuration=Release -p:Platform=x64 .

      - name: Build DLL ARM64X
        run: msbuild -m -target:VietTypeATL:Rebuild -p:Configuration=Release -p:Platform=ARM64EC .

      - name: Build Win32
        run: msbuild -m -target:VietTypeSetup:Rebuild -p:Configuration=Release -p:Platform=Win32 .

      - name: Build x64
        run: msbuild -m -target:VietTypeSetup:Rebuild -p:Configuration=Release -p:Platform=x64 .

      - name: Build ARM64X
        run: msbuild -m -target:VietTypeSetup:Rebuild -p:Configuration=Release -p:Platform=ARM64EC .

      - name: Upload a Build Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: VietTypeSetup/bin/
          name: VietType

    outputs:
      subject-name: VietType
      subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}

  attest:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    needs: [build]
    uses: dinhngtu/github-workflows/.github/workflows/attest.yml@af4b127febded0600cafa4f5935f99a24e267a8c
    permissions:
      id-token: write
      contents: read
      attestations: write
    with:
      subject-name: ${{ needs.build.outputs.subject-name }}
      subject-digest: ${{ needs.build.outputs.subject-digest }}
