name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SOLUTION_FILE_PATH: .

jobs:
  test:
    runs-on: "${{matrix.platform == 'ARM64EC' && 'windows-11-arm' || 'windows-latest'}}"
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
        platform:
          - Win32
          - x64
          #- ARM64EC

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup VSTest.console.exe
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          $vs = & "${Env:ProgramFiles(x86)}/Microsoft Visual Studio/Installer/vswhere.exe" -latest -property installationPath
          Add-Content $Env:GITHUB_PATH "$vs/Common7/IDE/Extensions/TestPlatform"

      - name: Build unit tests
        run: msbuild.exe -m -target:VietTypeUnitTests:Rebuild -p:Configuration=${{matrix.configuration}} -p:Platform=${{matrix.platform}} .

      - name: Run tests
        run: ${{matrix.platform == 'ARM64EC' && 'vstest.console.arm64.exe' || 'vstest.console.exe'}} ${{matrix.platform}}/${{matrix.configuration}}/VietTypeUnitTests.dll
