name: test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "VietTypeConfig2/**"
      - "VietTypeATL/**"
      - "VietTypeSetup/**"
      # unconditional
      - "TfDumper/**"
      - "WordLister/**"
      - "data/**"
      - "docs/**"
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: .

jobs:
  test:
    runs-on: "${{matrix.platform == 'ARM64EC' && 'windows-11-arm' || 'windows-latest'}}"
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
        platform:
          - Win32
          - x64
          #- ARM64EC

    steps:
      - uses: actions/checkout@v6

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Build unit tests
        run: msbuild.exe -m -target:VietTypeUnitTests:Rebuild -p:Configuration=${{matrix.configuration}} -p:Platform=${{matrix.platform}} .

      - name: Run tests
        run: |
          cd VietTypeUnitTests
          ../${{matrix.platform}}/${{matrix.configuration}}/VietTypeUnitTests.exe
